apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  labels:
    app: library-shop-pipelines
    group: rhacademy
  name: libray-shop
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: library-shop
  template:
    ref: library-shop