apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    group: rhacademy
    app: library-shop-pipelines
  name: library-shop-source
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi