---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  labels:
    app: library-shop-pipelines
    group: rhacademy
  name: library-shop
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef: library-shop