---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  labels:
    app: library-shop-pipelines
    group: rhacademy
  name: library-shop
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.clone_url)
  - name: git-repo-name
    value: $(body.repository.name)
  - name: git-revision
    value: $(body.head_commit.id)